?

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -35,6 +35,13 @@ jobs:
           -H 'Content-Type: application/json' \
           -d @key.json \
           https://iam.api.cloud.yandex.net/iam/v1/tokens | jq -r .iamToken)
+          
+          if [[ -z "$IAM_TOKEN" || "$IAM_TOKEN" == "null" ]]; then
+          echo "$IAM_TOKEN"
+          echo "ERROR: Failed to obtain IAM_TOKEN"
+          exit 1
+          fi
+          
           echo "$IAM_TOKEN" | docker login --username oauth --password-stdin cr.yandex
 
       - name: Set up Docker Buildx
